### PR TITLE
Fixed #42 and added a unit test.

### LINKED ISSUE #42: Incorrect page number of resumed entries in document TOC
If a certain chapter is so big that it spans three volumes or more, then there are two or more resumed entries for that chapter. It appears that these entries have the same page number in the document TOC, which is incorrect.
The page numbers of resumed entries in volume TOCs are ok.

### PR DESCRIPTION
**Pull request by PaulRambags**
Fixes #42 

@kalaspuffar @bertfrees Please review this PR, thank you

### CODE REVIEW

**Review by kalaspuffar — APPROVED** [review]

File: src/org/daisy/dotify/formatter/impl/volume/TocSequenceEventImpl.java [hunk 1]
```diff
@@ -168,7 +169,13 @@ public BlockSequence getBlockSequence(FormatterContext context, DefaultContext v
...
                             }
                             fsm.appendGroup(volumeStart);
-                            fsm.appendGroup(volumeToc);
+                            // If a chapter is so long that the there are two or
+                            // more resumed entries for that chapter in the
+                            // document TOC, the corresponding blocks must be
+                            // copied so that dynamic content (in particular
+                            // page numbers) is evaluated correctly. To avoid
+                            // code complexity, we simply copy all blocks here.
+                            fsm.appendGroup(volumeToc.stream().map(Block::copy).collect(Collectors.toList()));
```
Comment (bertfrees) [inline src/org/daisy/dotify/formatter/impl/volume/TocSequenceEventImpl.java]: Can you try if you can make it work by only copying the `Block` objects that match a `toc-entry-on-resumed`? That is, the `Block` objects returned by `TableOfContentsImpl.filter` that are contained in `rangeForBlock`.

If it is done that way it becomes more obvious what the issue is and how we prevent it from happening: we want to avoid that the same `Block` object (with the same computed content) is rendered multiple times at different places. This can happen with `toc-entry-on-resumed` blocks and also `on-volume-start` etc. blocks (see the copy call in `getCompoundIterableB()`), but not with normal `toc-entry` blocks.

Comment (PaulRambags) [reply src/org/daisy/dotify/formatter/impl/volume/TocSequenceEventImpl.java]: @bertfrees Done. Please review again.

Comment (bertfrees) [reply src/org/daisy/dotify/formatter/impl/volume/TocSequenceEventImpl.java]: I didn't know the block address also needed to be changed. But makes sense I guess. Complicates things a bit but it's OK.

**Review by bertfrees — APPROVED** [review]

File: src/org/daisy/dotify/formatter/impl/volume/TocSequenceEventImpl.java (hunk 1 above)
Comment (PaulRambags) [reply src/org/daisy/dotify/formatter/impl/volume/TocSequenceEventImpl.java]: >I didn't know the block address also needed to be changed. But makes sense I guess. Complicates things a bit but it's OK.

I think I forgot that in the first attempt to solve this issue...

**Review by kalaspuffar — APPROVED** [review]

**Comment by kalaspuffar** [comment]
Regression test ran and was excepted. Will now merge this PR.
